name: Validate customisation scripts

# Controls when the action will run. 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # Change back to Ubuntu once we fix the script
    runs-on: windows-2022
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run PowerShell commands
      - name: Get directory
        shell: pwsh
        run: |
          . .\ci\Install.ps1
          . .\ci\Build.ps1
          . .\ci\Tests.ps1
          . .\ci\Deploy.ps1

      - name: Push to repo
        uses: actions-x/commit@v2
        with:
          branch: main
          name: GitHubActions
          email: actions@stealthpuppy.com