name: Validate customisation scripts

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '!srv/VERSION.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches:
        - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: windows-2022
    #runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run Pester tests
      - name: Run Pester tests
        shell: powershell
        run: |
          . .\ci\Install.ps1
          . .\ci\Tests.ps1

      # Update version number in VERSION.txt
      - name: Update version number
        shell: powershell
        run: |
          . .\ci\Deploy.ps1

#      - name: Push to repo
#        uses: actions-x/commit@v2
#        with:
#          branch: main
#          name: GitHubActions
#          email: actions@stealthpuppy.com